version: '3.5'

services:
    texera:
        build:
            context: ../..
            dockerfile: ./core/docker/server/Dockerfile
        hostname: texera
        expose:
            - "8080"

    nginx-server:
        image: nginx:alpine-slim
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - texera
        ports:
            - "4000:4000"

    db:
        image: mysql:8
        hostname: texera-db
        volumes:
            # - ./mysql:/var/lib/mysql
            - ../scripts/sql/texera_ddl.sql:/docker-entrypoint-initdb.d/texera_ddl.sql
        environment:
            MYSQL_ROOT_PASSWORD: pass
            MYSQL_USER: texera
            MYSQL_PASSWORD: texera-pass
        ports:
            - "3305:3306"
